name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use the desired Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: fe/

      - name: Build frontend
        run: npm run bundleprod
        working-directory: fe/

      - name: Copy Files to Server
        run: |
          ssh -i ${{secrets.EC2_PRIVATE_KEY}} ${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}} \
            "mkdir -p ~/website" # Create target directory if not exists

          rsync -e "ssh -i ${{secrets.EC2_PRIVATE_KEY}}" -rL --delete \
            fe/dist_prod/ ${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}}:~/website/fe/

          rsync -e "ssh -i ${{secrets.EC2_PRIVATE_KEY}}" -rL --delete \
            be/ ${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}}:~/website/be/

      - name: Executing remote ssh commands using ssh key
        run: |
          ssh -i ${{secrets.EC2_PRIVATE_KEY}} ${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}} \
            "cd ~/website/fe && ls"
